server.port=8086
spring.application.name=api-gateway
spring.cloud.gateway.httpclient.response-timeout=30s

spring.cloud.gateway.routes[0].id=profile-service
spring.cloud.gateway.routes[0].uri=lb://profile-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/profiles/**
spring.cloud.gateway.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.name=profileServiceCircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.fallbackUri=forward:/fallback/profile

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://product-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/products/**
spring.cloud.gateway.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.name=productServiceCircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/fallback/product

spring.cloud.gateway.routes[2].id=cart-service
spring.cloud.gateway.routes[2].uri=lb://cart-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/carts/**
spring.cloud.gateway.routes[2].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.name=cartServiceCircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.fallbackUri=forward:/fallback/cart

spring.cloud.gateway.routes[3].id=order-service
spring.cloud.gateway.routes[3].uri=lb://order-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[3].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[3].filters[0].args.name=orderServiceCircuitBreaker
spring.cloud.gateway.routes[3].filters[0].args.fallbackUri=forward:/fallback/order

spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://notification-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[4].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[4].filters[0].args.name=notificationServiceCircuitBreaker
spring.cloud.gateway.routes[4].filters[0].args.fallbackUri=forward:/fallback/notification

spring.cloud.gateway.routes[5].id=wallet-service
spring.cloud.gateway.routes[5].uri=lb://wallet-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/wallets/**
spring.cloud.gateway.routes[5].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[5].filters[0].args.name=walletServiceCircuitBreaker
spring.cloud.gateway.routes[5].filters[0].args.fallbackUri=forward:/fallback/wallet

resilience4j.circuitbreaker.instances.profileServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.profileServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.profileServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.profileServiceCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.productServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.productServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.productServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productServiceCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.cartServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.cartServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.cartServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.cartServiceCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.walletServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.walletServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.walletServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.walletServiceCircuitBreaker.waitDurationInOpenState=10s
