server.port=8080
spring.application.name=website-controller
spring.thymeleaf.cache=false
app.gateway.base-url=${GATEWAY_BASE_URL:http://localhost:8086}
server.servlet.session.timeout=60m
spring.web.resources.cache.period=0
app.payment.upi-id=${PAYMENT_UPI_ID:eshoppingzone@upi}

github.oauth2.enabled=true

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23liGkIlv4cKA1PEtT}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:de694d20a2ece8f5237d0dfaef938759247569fc}
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.github.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.github.client-name=GitHub