server.port=8080
spring.application.name=website-controller
spring.thymeleaf.cache=false
app.gateway.base-url=${GATEWAY_BASE_URL:http://localhost:8086}
server.servlet.session.timeout=60m
spring.web.resources.cache.period=0
app.payment.upi-id=${PAYMENT_UPI_ID:eshoppingzone@upi}
